development:
  idp_sso_target_url:  https://thoughtworks.oktapreview.com/home/thoughtworks_sketchui_1/0oa341jtexVSIGHRNTDS/9517
  idp_cert_fingerprint: B8:53:D4:A7:E6:1B:86:FF:4E:91:F6:2D:34:EB:A6:A2:8F:89:9E:6F

test:
  idp_sso_target_url: https://thoughtworks.oktapreview.com/home/thoughtworks_sketchui_1/0oa341jtexVSIGHRNTDS/9517
  idp_cert_fingerprint: B8:53:D4:A7:E6:1B:86:FF:4E:91:F6:2D:34:EB:A6:A2:8F:89:9E:6F